import { PERMISSIONS } from "./Permissions";

export const ROLES = {
  WORKSPACE_OWNER: {
    id: "workspace_owner",
    name: "Workspace Owner",
    permissions: [
      PERMISSIONS.WORKSPACE_VIEW,
      PERMISSIONS.WORKSPACE_EDIT,
      PERMISSIONS.WORKSPACE_DELETE,
      PERMISSIONS.WORKSPACE_MANAGE_MEMBERS,
      PERMISSIONS.WORKSPACE_MANAGE_ADMINS,
      PERMISSIONS.WORKSPACE_CREATE,
      PERMISSIONS.WORKSPACE_CREATE_BOARD,

      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_EDIT,
      PERMISSIONS.BOARD_DELETE,
      PERMISSIONS.BOARD_MANAGE_MEMBERS,
      PERMISSIONS.BOARD_MANAGE_ADMINS_ADD,
      PERMISSIONS.BOARD_MANAGE_ADMINS_REMOVE,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.BOARD_COPY,
      PERMISSIONS.BOARD_DESCRIPTION,
      PERMISSIONS.BOARD_UPDATE_COVER,
      PERMISSIONS.BOARD_UPDATE_VISIBILITY,
      PERMISSIONS.BOARD_DETAILS,
      PERMISSIONS.BOARD_FAVOURITE,

      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_EDIT,
      PERMISSIONS.LIST_DELETE,
      PERMISSIONS.LIST_CREATE_CARD,
      PERMISSIONS.LIST_COPY,
      PERMISSIONS.LIST_MOVE,

      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_ATTACHMENT,
      PERMISSIONS.CARD_CHECKLIST,
      PERMISSIONS.CARD_DATE,
      PERMISSIONS.CARD_LABEL,
      PERMISSIONS.CARD_COPY,
    ],
  },

  WORKSPACE_ADMIN: {
    id: "workspace_admin",
    name: "Workspace Admin",
    permissions: [
      PERMISSIONS.WORKSPACE_VIEW,
      PERMISSIONS.WORKSPACE_EDIT,
      PERMISSIONS.WORKSPACE_MANAGE_MEMBERS,
      PERMISSIONS.WORKSPACE_CREATE_BOARD,

      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_EDIT,
      PERMISSIONS.BOARD_MANAGE_MEMBERS,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.BOARD_COPY,
      PERMISSIONS.BOARD_DESCRIPTION,
      PERMISSIONS.BOARD_UPDATE_COVER,
      PERMISSIONS.BOARD_UPDATE_VISIBILITY,
      PERMISSIONS.BOARD_FAVOURITE,

      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_EDIT,
      PERMISSIONS.LIST_CREATE_CARD,
      PERMISSIONS.LIST_COPY,
      PERMISSIONS.LIST_MOVE,

      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_ATTACHMENT,
      PERMISSIONS.CARD_CHECKLIST,
      PERMISSIONS.CARD_LABEL,
      PERMISSIONS.CARD_COPY,
    ],
  },

  WORKSPACE_MEMBER: {
    id: "workspace_member",
    name: "Workspace Member",
    permissions: [
      PERMISSIONS.WORKSPACE_VIEW,
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.WORKSPACE_CREATE_BOARD,

      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_MOVE,
    ],
  },

  BOARD_ADMIN: {
    id: "board_admin",
    name: "Board Admin",
    permissions: [
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_EDIT,
      PERMISSIONS.BOARD_MANAGE_MEMBERS,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.BOARD_COPY,
      PERMISSIONS.BOARD_DESCRIPTION,
      PERMISSIONS.BOARD_UPDATE_COVER,
      PERMISSIONS.BOARD_UPDATE_VISIBILITY,
      PERMISSIONS.BOARD_FAVOURITE,

      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_EDIT,
      PERMISSIONS.LIST_DELETE,
      PERMISSIONS.LIST_CREATE_CARD,
      PERMISSIONS.LIST_COPY,
      PERMISSIONS.LIST_MOVE,

      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_ATTACHMENT,
      PERMISSIONS.CARD_CHECKLIST,
      PERMISSIONS.CARD_LABEL,
      PERMISSIONS.CARD_COPY,
      PERMISSIONS.CARD_DATE,
      PERMISSIONS.CARD_JOIN
    ],
  },

  BOARD_MEMBER: {
    id: "board_member",
    name: "Board Member",
    permissions: [
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_CREATE_CARD,

      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_COPY,
      PERMISSIONS.CARD_JOIN

    ],
  },
  LIST_CREATOR: {
    id: "list_creator",
    name: "List creator",
    permissions: [
      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_EDIT,
      PERMISSIONS.LIST_CREATE_CARD,
      PERMISSIONS.LIST_COPY,
      PERMISSIONS.LIST_MOVE,

      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_JOIN

    ],
  },

  CARD_CREATOR: {
    id: "card_creator",
    name: "Card creator",
    permissions: [
      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_ATTACHMENT,
      PERMISSIONS.CARD_CHECKLIST,
      PERMISSIONS.CARD_LABEL,
      PERMISSIONS.CARD_DATE,
      PERMISSIONS.CARD_COPY,
    ],
  },
};
