import { PERMISSIONS } from "./Permissions";

export const ROLES = {
  WORKSPACE_OWNER: {
    id: "workspace_owner",
    name: "Workspace Owner",
    permissions: [
      PERMISSIONS.WORKSPACE_VIEW,
      PERMISSIONS.WORKSPACE_EDIT,
      PERMISSIONS.WORKSPACE_DELETE,
      PERMISSIONS.WORKSPACE_MANAGE_MEMBERS,
      PERMISSIONS.WORKSPACE_MANAGE_ADMINS,
      PERMISSIONS.WORKSPACE_CREATE_BOARD,
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_EDIT,
      PERMISSIONS.BOARD_DELETE,
      PERMISSIONS.BOARD_MANAGE_MEMBERS,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
    ],
  },

  WORKSPACE_ADMIN: {
    id: "workspace_admin",
    name: "Workspace Admin",
    permissions: [
      PERMISSIONS.WORKSPACE_VIEW,
      PERMISSIONS.WORKSPACE_EDIT,
      PERMISSIONS.WORKSPACE_MANAGE_MEMBERS,
      PERMISSIONS.WORKSPACE_CREATE_BOARD,
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_EDIT,
      PERMISSIONS.BOARD_MANAGE_MEMBERS,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
    ],
  },

  WORKSPACE_MEMBER: {
    id: "workspace_member",
    name: "Workspace Member",
    permissions: [
      PERMISSIONS.WORKSPACE_VIEW,
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.CARD_VIEW,
    ],
  },

  BOARD_ADMIN: {
    id: "board_admin",
    name: "Board Admin",
    permissions: [
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_EDIT,
      PERMISSIONS.BOARD_MANAGE_MEMBERS,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_EDIT,
      PERMISSIONS.LIST_DELETE,
      PERMISSIONS.LIST_CREATE_CARD,
      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_DELETE,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
      PERMISSIONS.CARD_ATTACHMENT,
      PERMISSIONS.CARD_CHECKLIST,
    ],
  },

  BOARD_MEMBER: {
    id: "board_member",
    name: "Board Member",
    permissions: [
      PERMISSIONS.BOARD_VIEW,
      PERMISSIONS.BOARD_CREATE_LIST,
      PERMISSIONS.LIST_VIEW,
      PERMISSIONS.LIST_CREATE_CARD,
      PERMISSIONS.CARD_VIEW,
      PERMISSIONS.CARD_EDIT,
      PERMISSIONS.CARD_MOVE,
      PERMISSIONS.CARD_COMMENT,
    ],
  },
};
